[package]
name = "uefi"
version = "0.1.0"
authors = ["Wonwoo Choi <chwo9843@gmail.com>"]
edition = "2018"

[dependencies]
bitflags = "1.0.4"
uefi-sys = { path = "../uefi-sys" }

[features]
default = ["alloc"]
alloc = []
